### PR TITLE
Refactored and re-written code

### PR DESCRIPTION
**Pull request by jaganadhg**
Hi Manaal Faruqui,
I am interested in your retrofitting project. To make it as a library with API I started re-writing the code.
Please review and merge i appropriate.

Also if possible please consider to revise the licence to MIT or BSD.

Best regards

Jagan

### CODE REVIEW

**Comment by mfaruqui** [comment]
Thanks!

Can you make 2 whitespaces as the default indentation everywhere? (instead of tabs ) I tend to follow Google style guide now and it asks to do that.

**Comment by jaganadhg** [comment]
Hi,
Made the changes.
One quick question, does the raw vector file generated after TF-IDF. Any guidance on creating a new one from a corpus. 
Best regards
Jagan

**Comment by mfaruqui** [comment]
I am not good at this github stuff. I am traveling to London tomorrow, I will get back to this soon.

**Comment by mfaruqui** [comment]
I am not good at this github stuff. I am traveling to London tomorrow, I will get back to this soon.

**Comment by mfaruqui** [comment]
I am not good at this github stuff. I am traveling to London tomorrow, I will get back to this soon.

**Comment by rajivgrover009** [comment]
Hi @mfaruqui ,

I came across your paper recently. Thanks for your work. 

I am trying to wrap my head around the python code. I have question on line# 74 in retrofit.py file. Why do we need to divide the newVec by 2*numNeighbors?

 ` newWordVecs[word] = newVec/(2*numNeighbours)`

Can you or anybody help me understand this? Much appreciated. 

Thanks!

**Comment by mfaruqui** [comment]
Please look at section 4 in the paper to see the values of alpha and beta that led to the code. The original equation is equation no. 1 in the paper.
http://www.manaalfaruqui.com/papers/naacl15-retrofitting.pdf

**Pull request closed without merging**
